# Generated by Django 2.2.2 on 2019-08-20 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curiosities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curiosities',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/materials/curiosities'),
            preserve_default=False,
        ),
    ]
