# Generated by Django 2.2.2 on 2019-06-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('date',)},
        ),
    ]
