# Generated by Django 2.2.2 on 2019-06-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190519_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',)},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='http://nutec.ufu.br/assets/images/group/user.png', upload_to='uploads/users'),
        ),
    ]
