# Generated by Django 2.1.7 on 2019-05-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='photo',
            field=models.ImageField(storage='uploads', upload_to='uploads/partners'),
        ),
    ]
