# Generated by Django 2.2.2 on 2019-06-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('name',)},
        ),
    ]
