# Generated by Django 2.1.7 on 2019-05-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20190519_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='photo',
            field=models.ImageField(upload_to='uploads/partners'),
        ),
    ]
