# Generated by Django 2.1.7 on 2019-04-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0002_auto_20190409_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time_init', models.TimeField()),
                ('time_end', models.TimeField()),
                ('number_users', models.IntegerField()),
                ('register', models.CharField(max_length=15)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiments.Experiment')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
